// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use serde::Serialize;
use serde::Deserialize;
use crate::model::diesel::ai::ai_schema::*;

#[derive(Insertable,Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
#[diesel(table_name = conversation)]
pub struct Conversation {
    pub id: i64,
    pub created_time: i64,
    pub title: String,
    pub updated_time: i64,
    pub user_id: i64,
}

#[derive(Insertable,Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
#[diesel(table_name = conversation_item)]
pub struct ConversationItem {
    pub id: i64,
    pub created_time: i64,
    pub question: Option<String>,
    pub updated_time: Option<i64>,
    pub answer: Option<String>,
    pub question_time: Option<i64>,
    pub answer_time: Option<i64>,
    pub cid: i64,
    pub req_id: Option<String>,
}

