apiVersion: v1
kind: Service
metadata:
  name: chat-hub-service
  namespace: reddwarf-pro
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: chat-hub-service
  clusterIP: 10.103.54.209
  clusterIPs:
    - 10.103.54.209
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
