# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli
[print_schema]
file = "../../src/model/diesel/ai/ai_schema.rs"
with_docs = false

filter = { only_tables = [
    "conversation",
    "conversation_item"
] }

